In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import polars as pl
import datetime as dt
from funx import RealFunction
from funx import TupleFunction
from funx.function.schema import Schema
from funx.function.data_types import TimestampType, RealType, TupleType, Field

In [3]:
df = pl.DataFrame([
    {"time": dt.datetime(2023, 10, 1, 12, 0), "altitude": 10.0, "nwp": {"temperature": 20.0, "wind_speed": 5.0, "pressure": 1013.25}},
    {"time": dt.datetime(2023, 10, 1, 13, 0), "altitude": 20.0, "nwp": {"temperature": 21.0, "wind_speed": 6.0, "pressure": 1013.25}},
    {"time": dt.datetime(2023, 10, 1, 14, 0), "altitude": 30.0, "nwp": {"temperature": 22.0, "wind_speed": 7.0, "pressure": 1013.25}},
    {"time": dt.datetime(2023, 10, 2, 12, 0), "altitude": 10.0, "nwp": {"temperature": 20.0, "wind_speed": 5.0, "pressure": 1013.25}},
    {"time": dt.datetime(2023, 10, 2, 13, 0), "altitude": 20.0, "nwp": {"temperature": 21.0, "wind_speed": 6.0, "pressure": 1013.25}},
    {"time": dt.datetime(2023, 10, 2, 14, 0), "altitude": 30.0, "nwp": {"temperature": 22.0, "wind_speed": 7.0, "pressure": 1013.25}},
])

In [4]:
dg = pl.DataFrame([
    {"time": dt.datetime(2023, 10, 1, 12, 0), "altitude": 10.0, "pressure": 1013.25},
    {"time": dt.datetime(2023, 10, 1, 13, 0), "altitude": 20.0, "pressure": 1012.75},
    {"time": dt.datetime(2023, 10, 1, 14, 0), "altitude": 30.0, "pressure": 1012.50},
])

In [5]:
f = TupleFunction(
    pl_df=df,
    schema=Schema(
        dims={"time": TimestampType(), "altitude": RealType()},
        name="nwp",
        dtype=TupleType([Field("temperature", RealType()), Field("wind_speed", RealType()), Field("pressure", RealType())]),
    )
)

In [6]:
g = RealFunction(
    pl_df=dg,
    schema=Schema(
        dims={
            "time": TimestampType(),
            "altitude": RealType(),
        },
        name="pressure",
        dtype=RealType(),
    )
)

In [7]:
TupleFunction.from_elements([f["temperature"], f["wind_speed"]])

Name:
	tuple
Data Type:
	(temperature, wind_speed) [real, real]
Dimensions:
	(time, altitude) [timestamp, real]