In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import polars as pl
import datetime as dt
import funx as fx

In [4]:
df = pl.DataFrame([
    {"time": dt.datetime(2023, 10, 1, 12, 0), "altitude": 10.0, "nwp": {"temperature": 20.0, "wind_speed": 5.0, "pressure": 1013.25}},
    {"time": dt.datetime(2023, 10, 1, 13, 0), "altitude": 20.0, "nwp": {"temperature": 21.0, "wind_speed": 6.0, "pressure": 1013.25}},
    {"time": dt.datetime(2023, 10, 1, 14, 0), "altitude": 30.0, "nwp": {"temperature": 22.0, "wind_speed": 7.0, "pressure": 1013.25}},
    {"time": dt.datetime(2023, 10, 2, 12, 0), "altitude": 10.0, "nwp": {"temperature": 20.0, "wind_speed": 5.0, "pressure": 1013.25}},
    {"time": dt.datetime(2023, 10, 2, 13, 0), "altitude": 20.0, "nwp": {"temperature": 21.0, "wind_speed": 6.0, "pressure": 1013.25}},
    {"time": dt.datetime(2023, 10, 2, 14, 0), "altitude": 30.0, "nwp": {"temperature": 22.0, "wind_speed": 7.0, "pressure": 1013.25}},
])

In [5]:
dg = pl.DataFrame([
    {"time": dt.datetime(2023, 10, 1, 12, 0), "altitude": 10.0, "pressure": 1013.25},
    {"time": dt.datetime(2023, 10, 1, 13, 0), "altitude": 20.0, "pressure": 1012.75},
    {"time": dt.datetime(2023, 10, 1, 14, 0), "altitude": 30.0, "pressure": 1012.50},
])

In [6]:
f = fx.make_function(
    df,
    dims={
        "time": fx.TimestampType(),
        "altitude": fx.RealType(),
    },
    dtype=fx.TupleType({
        "temperature": fx.RealType(),
        "wind_speed": fx.RealType(),
        "pressure": fx.RealType()
    }),
    expr=pl.col("nwp"),
)

In [7]:
g = fx.make_function(
    dg,
    dims={
        "time": fx.TimestampType(),
        "altitude": fx.RealType(),
    },
    dtype=fx.RealType(),
    expr=pl.col("pressure"),
)

In [18]:
g.join(g.alias("x"))